clone:
  git:
    image: plugins/git
    depth: 50
    recursive: false

pipeline:
  laravel:
    image: laradock/workspace:1.8-71
    group: backend
    commands:
      - php -v
      - composer -V
      - cp .env.example .env
      - composer install --prefer-dist --no-dev
      - php artisan key:generate
      - php artisan migrate

services:
  mysql:
    image: mysql:5.7.21
    environment:
      - MYSQL_DATABASE=drone-laravel-mysql
      - MYSQL_ROOT_PASSWORD=password